---
# - name: Create Repository Play
#   hosts: ise_deployment
#   vars_files:
#     - credentials.yaml
#   gather_facts: no
#   tasks:


  - name: Create Repository "{{ name }}"
    cisco.ise.repository:
      ise_hostname: "{{ inventory_hostname }}"
      ise_username: "{{ ise_username }}"
      ise_password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
      state: present
      name: "{{ name }}"
      serverName: "{{ serverName }}"
      protocol: "{{ protocol }}"
      path: "{{ path }}"
      userName: "{{ userName }}"
      password: "{{ password }}"
      enablePki: "{{ enablePki }}"
    register: result

  # - name: Result
  #   ansible.builtin.debug: var=result

